activity/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns =[
    path('activity/',views.add_activity, name='add_activity' ),
    path('data/', views.detail_activity, name='detail_activity'),
]

jadwal/urls.py
from django.urls import path
from . import views

app_name = 'jadwal'

urlpatterns = [
    path('add/', views.add_jadwal, name='add_jadwal'),
    path('view_jadwal/', views.view_jadwal, name='view_jadwal'),
    path('delete/<id>', views.delete_jadwal, name='delete_jadwal'),
    path('detail/<id>', views.detail, name='detail'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('story9.urls'), name='accounts'),
    path('', TemplateView.as_view(template_name='buku.html'), name='buku'),
    path('', include('story3.urls')),
    path('story-3/', include('story1.urls')),
    path('schedule/', include('jadwal.urls')),
    path('activity/', include('activity.urls')),
    path('story7/', include('story7.urls')),
    path('', include('story8.urls'))
    
]

story1/urls.py
from django.urls import path
from . import views

app_name = 'story1'

urlpatterns = [
    path('story-1', views.DeijaProfile, name='DeijaProfile'),
  
]

story3/urls.py
from django.urls import path
from . import views

app_name = 'story3'

urlpatterns = [
    path('', views.buku, name='buku'),
    path('profile/', views.index, name='index'),
   
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.accordion, name='accordion'),
    
   
]

story8/urls.py
from django.urls import path

from . import views

app_name = 'story8'

urlpatterns = [
    path('book_search', views.book_search, name='book-search'),
    path('data', views.book_data, name='book-data')

]

story9/urls.py
from django.urls import path
from .views import signUpView
from . import views

app_name = 'story9'

urlpatterns = [
    path('signup', signUpView.as_view(), name='signup'),
    path('hi', views.hi , name='hi'),
]

activity/models.py
from django.db import models


# Create your models here.
class Activity(models.Model):
    activity = models.CharField('Activity', max_length=100)

    # class Meta:
    #     db_table = 'activity'

    def __str__(self):
         return self.activity


class Participant(models.Model):
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE) #link 2 tables together
    name = models.CharField('Partisipan', max_length=50)

    # #class Meta:
    #     db_table = 'participant'

    def __str__(self):
        return self.name

jadwal/models.py
from django.db import models

# Create your models here.
class Jadwal(models.Model):
    Subject = models.CharField(max_length=50)
    Lecturer = models.CharField(max_length=50)
    Credits = models.CharField(max_length=50)
    Description = models.TextField(max_length=250)
    Semester = models.CharField(max_length=50)
    Room = models.CharField(max_length=50)
    

story1/models.py
from django.db import models

# Create your models here.

story3/models.py
from django.db import models

# Create your models here.

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

activity/forms.py
from django import forms
from .models import Activity, Participant

class ActivityForm(forms.ModelForm):
    class Meta :
        model = Activity
        fields = '__all__'
        # widgets = {
        #     'activity': forms.Select(attrs={'class':'form-control'})
        # }

class ParticipantForm(forms.ModelForm):
    class Meta :
        model = Participant
        fields = '__all__'
        # widgets = {
        #     'activity': forms.Select(attrs={'class':'form-control'})
        #     "name" : forms.TextInput(attrs={'class':'form-control'})
        # }

jadwal/forms.py
from django import forms

from .models import Jadwal

class JadwalForm(forms.ModelForm):
    class Meta:
        model = Jadwal
        fields=['Subject','Lecturer','Credits','Description','Semester','Room']
        widgets={
            'Subject' :forms.TextInput(attrs={'class':'form-control'}),
            'Lecturer' :forms.TextInput(attrs={'class':'form-control'}),
            'Credits' :forms.TextInput(attrs={'class':'form-control'}),
            'Description' :forms.TextInput(attrs={'class':'form-control'}),
            'Semester' :forms.TextInput(attrs={'class':'form-control'}),
            'Room' : forms.TextInput(attrs={'class':'form-control'}),
        } 

activity/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Activity, Participant
from .forms import ActivityForm, ParticipantForm

# Create your views here.
def add_activity(request):
    form = ActivityForm()
    if request.method == 'POST':
        inputform = ActivityForm(request.POST)
        if inputform.is_valid():
            inputform.save()
            return render(request, 'add_activity.html',{'form': form,'status':'success', 'data' : Activity.objects.all()})
        else :
            return render(request, 'add_activity.html',{'form':form, 'status':'failed', 'data': Activity.objects.all()})
    else :
        current_data = Activity.objects.all()
        return render(request, 'add_activity.html', {'form':form, 'data':current_data})

def detail_activity(request):
    form = ParticipantForm()
    act_data = Activity.objects.all()
    ptc_data = Participant.objects.all()
    if request.method == 'POST':
        inputform = ParticipantForm(request.POST)
        if inputform.is_valid():
            inputform.save()
            return redirect(detail_activity)
        else:
            participantData = Participant.objects.all()
            return render(request, 'detail_activity.html', {'form':form, 'status': 'failed', 'participantData' : ptc_data, 'activityData': act_data })
    else:
        return render(request,'detail_activity.html', {'form':form, 'status': 'failed', 'participantData' : ptc_data, 'activityData': act_data})

jadwal/views.py
from django.shortcuts import render, redirect
from .models import Jadwal
from .forms import JadwalForm

# Create your views here.
def add_jadwal(request):
    if request.method == 'POST':
        form = JadwalForm(request.POST)
        if form.is_valid():
            jadwal = form.save()
            jadwal.save()
            return redirect('jadwal:view_jadwal')
    else:
        form = JadwalForm()
        
    return render(request,'add_jadwal.html',{'form' : form})

def view_jadwal(request):
    semua_jadwal = Jadwal.objects.order_by('Subject')
    return render(request,'view_jadwal.html',{'semua_jadwal': semua_jadwal})

def delete_jadwal(request,id):
    Jadwal.objects.get(id=id).delete()
    return redirect('jadwal:view_jadwal')

def detail(request,id):
    detail = Jadwal.objects.get(id=id)
    return render(request,'detail.html',{'detail': detail})

story1/views.py
from django.shortcuts import render

# Create your views here.
def DeijaProfile(request):
    return render(request, 'DeijaProfile.html')

story3/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

def buku(request):
    return render(request, 'buku.html')

story7/views.py
from django.shortcuts import render

# Create your views here.

def accordion(request):
    return render(request, 'accordion.html')

story8/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse, JsonResponse
import requests


# Create your views here.

def book_search(request):
    return render(request, 'book_search.html')

def book_data(request):
    buku = request.GET['buku']
    url_tujuan = 'https://www.googleapis.com/books/v1/volumes?q=' + buku
    # r = requests.get(url_tujuan)
    # data = json.loads(r.content)
    result = requests.get(url_tujuan)
    data = result.json()
    return JsonResponse(data, safe=False)

story9/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.

def hi(request):
    return render(request, "awal.html")

class signUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

jadwal/templates/view_jadwal.html
<!doctype html>
{% extends 'index.html' %}
{% load static %}
<html lang="en">
  <head>
    <title>Deija's Portofolio</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- My fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet"> 

    <!-- My CSS -->
    {% block meta%}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    {% endblock meta %}

    <style>
        body {
            font-family:'Montserrat', sans-serif !important;
            font-size: 15px;
            font-weight: bold;
            margin: 0 30px;
        }
    </style>
    <!-- akhir style -->
    </head>

    <body>
    
   <!-- view matkul -->
   {% block content %}
    <div style="margin-top:7em">
     <table class="table table-striped ">
         <thead>
             <tr>
                 <th scope="col">Subject</th>
                 <th scope="col">Lecturer</th>
                 <th scope="col">Credits</th>
                 <th scope="col">Description</th>
                 <th scope="col">Semester</th>
                 <th scope="col">Room</th>
                 <th scope="col">Delete</th>
             </tr>
         </thead>
         <tbody>
             {% for jadwal in semua_jadwal %}
             <tr>
                 <td>
                     <a href="{% url 'jadwal:detail' id=jadwal.id %}">{{ jadwal.Subject }}</a>
                 </td>
                 <td>{{ jadwal.Lecturer}}</td>
                 <td>{{ jadwal.Credits}}</td>
                 <td>{{ jadwal.Description}}</td>
                 <td>{{ jadwal.Semester}}</td>
                 <td>{{ jadwal.Room}}</td>
            <td>
                <a style="background-color: black; color:white" href="{% url 'jadwal:delete_jadwal' id=jadwal.id %}" role="button">Delete Subject</a>
            </td>
             </tr>
             {% endfor %}
         </tbody>
     </table>   
    </div>
    {% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

  </body>
</html>

story1/templates/DeijaProfile.html
<!DOCTYPE html>
{% extends 'index.html' %}
{% load static %}

<html>

    <head>
        <title>
            Deija Profile
        </title>
         <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- My fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet"> 

    <!-- My CSS -->
    {% block meta%}

    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    {% endblock meta %}
        <style>
            body{
                background-color: beige;
            }
        </style>
    </head>

    <body>
        {% block content %}
        <header>
        <img src="{% static 'deijafoto.jpg' %}" style="width : 300px; height : 400px; position:absolute;top: 200px;left: 50px;">
        <img src="{% static 'makara-ui-fasilkom.png' %}" style="width : 300px; height : 300px; position:absolute;top: 250px;right: 50px;">
        <center>
            <div style="margin-top:10em">
            <h1 >Deija Shakina Ayu</h1>
            <h3>NPM = 1906399373</h3>
            <h3>Angkatan = 2019</h3>
            <h3>Tempat Kuliah = Universitas Indonesia</h3>
            <h3>Hobi = menonton Netflix</h3>
            <br>
            <h3>Riwayat Pendidikan</h3>
            <table class="text-center" align="center">
                <tr>
                    <th>Tahun</th>
                    <th>Pendidikan</th>
                    <th>Jurusan</th>
                </tr>
                <tr>
                    <td>2005-2007</td>
                    <td>TK Perguruan Cikini</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>2007-2013</td>
                    <td>SD Perguruan Cikini</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>2013-2016</td>
                    <td>SMP Labschool Kebayoran</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>2016-2019</td>
                    <td>SMA Labschool Kebayoran</td>
                    <td>IPA</td>
                </tr>
                <tr>
                    <td>2019- sekarang</td>
                    <td>Universitas Indonesia</td>
                    <td>Fasilkom-Sistem Informasi</td>
                </tr>
            </table>
            <br>
            <h3>Sedikit Tentang Saya</h3>
            <p>Saya adalah orang yang sangat suka bercanda bersama teman.<br>
                Akhir- akhir ini sayang sedang sering-seringnya bermain<br>
                Among Us bersama teman-teman karena itu sangat menyenangkan<br>
                Saya sangat bersyukur dengan apa yang telah saya punya sekarang.
            </p>
        </div>
            <br>
            <h3>Social Media</h3>
            <br>
            <div style="margin: auto; width: 200px;" align = "center">
            <a href="https://www.instagram.com/deijashakinaayu/"><img src="https://i.pinimg.com/originals/a2/5f/4f/a25f4f58938bbe61357ebca42d23866f.png" width="50" height="50"></img></a>
            <a href="https://wa.me/6287781019778"><img src="https://pngimg.com/uploads/whatsapp/whatsapp_PNG11.png" width="45" height="44"></img></a>
            <a href="https://line.me/R/ti/p/deijashakinaayu"><img src="https://1.bp.blogspot.com/-QHm3gv3zc0U/XyvL9d7C-VI/AAAAAAAACl8/OkKXjwmahkEs5E-AUt7ZGtCN1CZhjycxwCLcBGAsYHQ/s1600/Logo%2BLINE.png" width="60" height="50"></img></a>
            </div>
            <br>
            <div>
                <a href="{% url 'story3:index' %}"><h>Back to home</h></a>
            </div>
        </center>
        {% endblock content %}
         <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    </body>

</html>

story3/templates/index.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <title>Deija's Portofolio</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- My fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet"> 

    <!-- My CSS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    {% block meta%}

    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    {% endblock meta %}
    <style>
      body {
          font-family:'Montserrat', sans-serif !important;
          font-size: 15px;
          font-weight: bold;
          margin: 0 30px;
      }
      .nav-link:hover::after {
          content: '';
          display: block;
          border-bottom: 3px solid rgb(54, 54, 54);
          width: 50%;
          margin: auto;
          padding-bottom: 5px;
      
      }

      .navbar-brand{
          width: 70%;
      }

      .navbar-expand-lg .navbar-nav .nav-link {
        padding : 0 1em;
      }

      .title {
        top: 4em;
        font-size: 60px;
        font-weight: bold;
        /* border-bottom: 3px solid black; */
        /* width:50%; */
      }

      .title-2 {
        top: 5em;
        font-size: 30px;
        font-weight: bold;
        /* border-bottom: 3px solid black; */
        /* width:50%; */
      }

      .btn-2{
        color: white;
        margin-left:70em; 
        margin-top:45em; 
        background-color: black;
        border-radius: 25px;
        border-color: black;
      }

      .text-overlay {
        position: absolute;
        top: 9em;
        left: 4.8em;
        right: 1.5em;
        font-size : 10px;
      }


      .margin-gambar{
        margin-top: 2.5em;
        
      }

      .social-media{
        width: 20%;

      }



    </style>
    <!-- akhir style -->
    
    </head>
    <body>


      <!-- Navbar -->
      <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-transparent" style="color:rgb(54, 54, 54)">
        <div class="container">
            <a class="navbar-brand page-scroll" href="{% url 'story3:index' %}"><img src="{% static 'logo2.png' %}" alt="logonavbar"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                <a class="nav-link" href="{% url 'story3:index' %}">Home<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="#about">About</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="#education">Education</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#contact">Contact</a>
                  </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'story1:DeijaProfile' %}">story1</a>
                    </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'jadwal:add_jadwal' %}">Add</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'jadwal:view_jadwal' %}">View</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'add_activity' %}">Activity</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'story7:accordion' %}">Facts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'story8:book-search' %}">BookSearch</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">LOGIN</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'story9:signup' %}">signup</a>
        {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
        {% else %}
        <a class="nav-link"  href="{% url 'login' %}">Log In</a>
        {% endif %}
    </li>
      
                <!-- <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Schedule
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                      <a class="dropdown-item" href="#">My Schedule</a>
                      <a class="dropdown-item" href="#">Add Schedule</a>
                </li> -->
            </ul>
            </div>
        </div>
    </nav>
      <!-- Akhir navbar -->

      <!-- section 1 -->
      {% block content %}
      <section class="section1" id="home-page" style="padding-top: 6em">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <div style="text-align:center;margin-top:3em;">
                <p style="margin-top:4em" class="title">welcome :)</p>
              </div>
            </div>
            <div class="col-md-6">
              <img style="width:100%; margin-top: 3em;" src="{% static 'gambar1.jpg' %}" alt="My Image">
              <div class="text-overlay">
                <p style="color:rgb(255, 255, 255)"><p style="color:rgb(255, 255, 255)">work portofolio<br><br><br>Hey guys, you could check-out my Profile and Check Out my<br> latest art work, hope you guys like it and if you guys are not,<br>I know why.</p></p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <!-- akhir section 1 -->

      <!-- section 2 -->
      <section class="section2" id="about">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
                <img class="margin-img" style="width:100%; margin-top: 9em; margin-left: 10em;"  src="{% static 'about.png' %}">
                <div class="text-overlay">
                  <button class="btn-2">my work</button>
                </div>
            </div>
          </div>
        </div>
        </div>
        </section>
      </section>
      <!-- akhir sec 2 -->

      <!-- section 3  -->
      <section style="margin-top: 2em;"class="section3" id="education">
        <div class="container">
          <div class="row">
              <div class="col-md-6">
                <img style="width:100%; margin-top: 7em; margin-left:0" src="{% static 'gambar1.jpg' %}">
                </div>
                <div class="col-md-6">
                  <div style="text-align:center;margin-top: 4em;">
                    <p style="margin-top: 5em" class="title-2">Educational<br>Background<br><br></br.><img style="width:100%" src="{% static 'degree.jpg' %}"></p>
                    <div style="text-align: center;margin-top: 4em;"></div>
                  </div>
                </div>
            </div>
          </div>
      </section> 
      <!-- akhir section 3 -->

      <!-- section 4 -->
      <section class="section4" id="contact">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <div style="text-align:center; margin-top:4em">
                <p style="margin-top: 5em;" class="title">
                  Contact Me<br>
                </p>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <a href="https://www.instagram.com/deijashakina/">
              <img class="social-media" src="{% static 'ig.png' %}">
            </a>
            <a href="http://line.me/ti/p/~deijashakinaayu">
              <img class="social-media" src="{% static 'line.png' %}">
            </a>
            <a href="https://wa.me/6287781019778">
              <img style="width:14%; margin-left:1.5em" src="{% static 'whatsapp.png' %}">
            </a>
            </div>
          </div>
        </div>
      </section>
      <!-- akhir section 4 -->
      {% endblock content %}

    
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

  </body>
</html>

story8/templates/book_search.html
{% extends 'index.html' %}
{% load static %}

{% block head %}
<title>Book Search</title>

<!-- <script src="{% static 'statc/js/story8.js'%}" type='text/javascript'></script> -->

{% endblock head %}

{% block sidebar %}
{% endblock sidebar %}

{% block content %}

<div class="wrapper-page" style="margin-top: 7em;">
  <h1 class="abril-font" style="font-size: 60px; font-weight: bold;">Book Search</h1>
  <div class="align-content-center" > 
    <input class="form-control form-inline" type="text" id="keyword" placeholder="Book...">
    <input class="form-control form-inline btn btn-primary click" style="margin-top: 20px; width: 50%;" type="button" id="search" value="Search">    
  </div>
</div>

<div class="card shadow mb-5" style="margin:5vw;">
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-hover" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>No.</th>
              <th>Title</th>
              <th>Author(s)</th>
              <th>Description</th>
              <th>Image</th>
            </tr>
          </thead>
          <tbody id="book-data"></tbody>
      </div>
    </div>
</div>
</div>


<script type = "text/javascript" src= "{% static 'js/story8.js'%}"></script>
{% endblock content %}